// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz-BwR8hODTkjvCOTkGGaYaPN7HJ766hg',
    appId: '1:336190760076:web:703dbc3730a1cd23dfc7a9',
    messagingSenderId: '336190760076',
    projectId: 'food-bazaar-89c4b',
    authDomain: 'food-bazaar-89c4b.firebaseapp.com',
    storageBucket: 'food-bazaar-89c4b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN7nL7Ngz6BsxO8ZsUTEKPNbGjEyur4K4',
    appId: '1:336190760076:android:c18875757963bf7fdfc7a9',
    messagingSenderId: '336190760076',
    projectId: 'food-bazaar-89c4b',
    storageBucket: 'food-bazaar-89c4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXT7cx20BNu_fQui0pFCQzoJVlNUPpPqI',
    appId: '1:336190760076:ios:10f23aac46a5ac25dfc7a9',
    messagingSenderId: '336190760076',
    projectId: 'food-bazaar-89c4b',
    storageBucket: 'food-bazaar-89c4b.appspot.com',
    iosBundleId: 'com.example.biteBazaar',
  );
}
